### PR TITLE
fix for 11-usart

### LINKED ISSUE #264: 11-usart None on Peripherals take
Hi there,
I'm trying to run an example code from `11-usart` section without using external serial module;
Unfortunately, I still cannot get "x" printed in Minicom, also I've noticed that `11-usart/auxiliary/src/lib.rs:18` which is `let cp = cortex_m::Peripherals::take().unwrap();` panics with `None`.

Could you please help me with that?

### PR DESCRIPTION
**Pull request by zhao-lang**
@paulkernfeld should fix #264 

`11-usart` was panicking on the older version of `cortex-m`, updating to `0.6.3` fixes that, but introduces incompatibilities with the `f3` crate. I replaced the `f3` crate with the newer `stm32f3xx-hal`. Also had to add `memory.x` to project root in order to get things to compile, maybe there's a better solution for that?

### CODE REVIEW

**Comment by eldruin** [comment]
FYI, we are looking at a major rewrite of this book since the STM32F3Discovery boards have become difficult to buy. We may choose the [micro:bit](https://tech.microbit.org/hardware/) board as a replacement. See #263

**Comment by andre-richter** [comment]
I am not familiar with the cortex-m stuff. Temporarily switching my assignment mit @adamgreig. Adam, please see if you can review or delegate this. Thanks :)

**Comment by bitdivine** [comment]
@andre-richter Is someone else available to review this?  I assume that @adamgreig is busy.

**Comment by adamgreig** [comment]
Ugh, sorry, this totally fell off my radar. I think there's two issues merging this as-is:

1. It requires an additional change to `11-usart/src/main.rs` to put the call to `tdr().bits()` into an unsafe block (and also removing the `#[deny(unsafe_code)]` attribute at the top), but sticking that unsafe code in seems quite confusing to newcomers and would need explaining (why do we need it here but not elsewhere, etc)
2. I guess memory.x was being provided by the HAL, but we shouldn't then stick a new one in the repository root. We could probably place it inside the `11-usart/` directory along with a `build.rs` script to copy it to the linker directory.

For the second point I think we can just swap the dependency to the new `stm32f3-discovery` crate and update the exports to `stm32f3_discovery::stm32f3xx_hal::...`, so we don't need a `memory.x` at all.

However I think we still need the unsafe block which isn't great... looking into it it seems like an error in the stm32f3 crate where the TDR register is said to be safe for any value 0-255 but as it's a nine-bit register it should actually go to 0x1ff. Dunno why that's not been caught before to be honest... but it won't be a quick update, so for now I guess we're stuck with the unsafe block.

**Comment by adamgreig** [comment]
This has now been fixed by #354, thank you for starting the work in this PR!

**Pull request closed without merging**
