### PR TITLE
Update .cargo/config diff baseline

### PR DESCRIPTION
**Pull request by adamgreen**
The diff in 06-hello-world/README.md for changes to be made to
.cargo/config are based off of an older version of the config file than
what is found in the repository currently.

### CODE REVIEW

**Comment by adamgreig** [comment]
Should we leave out `"-C", "linker=rust-lld"` entirely?

**Comment by adamgreen** [comment]
I take it that **rust-lld** is the default linker anyway so this option is no longer required? If you guys decide that you would like to have that line removed from all of the .cargo/config files then I can make that change too. Just let me know.

**Comment by adamgreen** [comment]
@adamgreig I have added commit 419ce796a121d0863721b19abca30f1b4ede02d2 to this PR to remove the ```"-C", "linker=rust-lld"``` flag completely from the .cargo/config files and mark down documentation.

I made sure that ```cargo build --target thumbv7em-none-eabihf``` at the root of the project still runs successfully and then took one of the resulting binaries and ran it on my Discovery board.

Thanks for the feedback!

**Comment by adamgreig** [comment]
Great, thanks!

bors r+

**Pull request merged**
