### PR TITLE
Avoid pulling in microbit 0.13

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by hargoniX** [comment]
If microbit already made a release upstream I don't see any reason to pull directly from git anymore, could we change it so that it uses crates.io like the other dependencies?

**Comment by shepmaster** [comment]
Updated

**Review by hargoniX — APPROVED** [review]

**Comment by hargoniX** [comment]
Looks good to me, thanks!
bors r+

**Comment by therealprof** [comment]
What's so bad about 0.13?

**Comment by hargoniX** [comment]
If 0.13 is fine we can pull it in as well, I just wanted to cut the pulling code in from Github in general.

**Comment by therealprof** [comment]
Cool, I was just worried there was a problem with 0.13. I've heard people ran into problems using `defmt` 0.2 with new `probe-rs` tooling which was the main reason to remove `rubble` and update `defmt` in the latest `microbit`.

**Pull request merged**
