### PR TITLE
merge upstream

### PR DESCRIPTION
**Pull request by tomoyuki-nakabayashi**

### CODE REVIEW

**Comment by tomoyuki-nakabayashi** [comment]
I made a mistake. This should be merged my fork repository...

**Comment by adamgreig** [comment]
Oh, I didn't know about the translation work, nice! Should we link to it from the main book website?

**Comment by tomoyuki-nakabayashi** [comment]
Thanks your kind reply!

I would be very happy if the rust-embedded team would handle the translations, as TRPL is doing.
https://github.com/rust-lang/book#translations

I've translated Discovery book (only f3, I just started micro:bit version), the Embedded Rust book, and The Embedonomicon into Japanese.

**Comment by adamgreig** [comment]
Wow, great work, thank you!

It looks like TRPL has an active branch/PR for each language, but won't merge any until mdbook supports more languages. If you want to host your translations on GitHub Pages, I'd be very happy to link to it from the front pages of our version, or we could try and host the translations on our site too if you like, maybe have a subdirectory for each language that is built as a separate book and linked (until mdbook supports choosing language).

**Comment by tomoyuki-nakabayashi** [comment]
I'm currently hosting GitHub Pages, so I prefer to make links from the original.
Here, hosting pages and repos (or should I create PR?)

- https://tomoyuki-nakabayashi.github.io/discovery/
  - https://github.com/tomoyuki-nakabayashi/discovery
- https://tomoyuki-nakabayashi.github.io/book/
  - https://github.com/tomoyuki-nakabayashi/book
- https://tomoyuki-nakabayashi.github.io/embedonomicon/
  - https://github.com/tomoyuki-nakabayashi/embedonomicon

**Pull request closed without merging**
