### PR TITLE
Upgrade most aux crates to cortex-m 0.6.3

### PR DESCRIPTION
**Pull request by paulkernfeld**
This should fix issue #259 in all chapters except 11 and 16.

### CODE REVIEW

**Comment by paulkernfeld** [comment]
I know that it would be better to fix #259 for all chapters but it seems like there might be a longer discussion involved there so I thought this would be a decent stopgap until then. 😊

**Comment by paulkernfeld** [comment]
Sorry, I meant to not upgrade chapter 16, but I accidentally did. I think that failed the build.

**Comment by paulkernfeld** [comment]
@therealprof could you take another look at this? It looks like the bors check hasn't run; could it be stuck or do I need to take some action?

**Comment by therealprof** [comment]
bors try

**Pull request merged**
